import classNames from "classnames";
import "./globals.css";
import { Work_Sans } from "next/font/google";

const worksans = Work_Sans({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={classNames(
					worksans.className,
					"theme-green bg-black",
				)}
			>
				{children}
			</body>
		</html>
	);
}
